"""add fields to admins

Revision ID: 9b710ee0c0ef
Revises: f02194c811d6
Create Date: 2026-06-04 10:14:55.297881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b710ee0c0ef'
down_revision = 'f02194c811d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_choose_group', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_set_traffic_limit', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_set_date_expire', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_use_templates', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_change_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_change_temporary_status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('can_change_temporary_status')
        batch_op.drop_column('can_change_status')
        batch_op.drop_column('can_use_templates')
        batch_op.drop_column('can_set_date_expire')
        batch_op.drop_column('can_set_traffic_limit')
        batch_op.drop_column('can_choose_group')

    # ### end Alembic commands ###
