"""Add temporary_status field to users

Revision ID: e2b35e632a3c
Revises: 9b710ee0c0ef
Create Date: 2026-06-07 12:09:01.311460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b35e632a3c'
down_revision = '9b710ee0c0ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_status', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temporary_status')

    # ### end Alembic commands ###
